# Generated by Django 3.0.8 on 2020-08-21 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ART', 'Art'), ('ANT', 'Antiques'), ('COL', 'Collectibles'), ('FAS', 'Fashion'), ('GAM', 'Games'), ('MIS', 'Miscelaneous'), ('MOV', 'Movies'), ('MUS', 'Music Gear & Equipment'), ('SPO', 'Sporting Goods'), ('TOY', 'Toys')], default='MIS', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(null=True)),
                ('current_bid', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=256, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings_in_category', to='auctions.Category')),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_listings', models.ManyToManyField(blank=True, related_name='watchlists', to='auctions.Listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='related_watchlists',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.Watchlist'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(default=0)),
                ('associated_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.Listing')),
                ('bid_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
