# Generated by Django 3.0.8 on 2020-08-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200821_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_object',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.Bid'),
        ),
    ]
