# Generated by Django 3.0.8 on 2020-08-21 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_bid_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
