# Generated by Django 3.0.8 on 2020-08-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_associated_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_object',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.Bid'),
        ),
    ]
