# Generated by Django 3.0.8 on 2020-08-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_open',
            field=models.BooleanField(default=True),
        ),
    ]
