# Generated by Django 3.0.8 on 2020-08-22 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_auction_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid_object',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_listing', to='auctions.Listing'),
        ),
    ]
